awesomeproject/awesomeproject/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from sudentapp.views import IndexView
from django.conf import settings
from django.conf.urls.static import static

from  django.contrib.auth.views import LoginView
from rest_framework.routers import DefaultRouter
from sudentapp.views import DishViewSet,IngredientViewSet

router = DefaultRouter()
router.register(r'dish', DishViewSet)
router.register(r'ingredient',IngredientViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('',IndexView.as_view()),
    path('accounts/login/',LoginView.as_view(template_name="login.html"),name="login"),
    path('dish/',include("sudentapp.urls")),
    path('admin/', admin.site.urls),
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

awesomeproject/sudentapp/urls.py
from django.urls import path
from sudentapp.views import( DishListView,
                            DishDetailView,
                            DishCreateView,
                            create_view,
                            DishUpdateView,
                            dish_list_json,
                            food_list_json,
                            like
                            )

urlpatterns = [
    path('',DishListView.as_view(),name="dish-list0"),
    path('like/',like,name="dish-like"),
    path('json/',dish_list_json,name="dish-list-json"),
    path('food/json/',food_list_json,name="food-list-json"),
    #path('create',DishCreateView.as_view(),name="dish-create"),
    path('create',create_view,name="dish-create0"),
    path('<int:pk>/class',DishDetailView.as_view(),name="dish-detail0"),
    path('<int:pk>/update',DishUpdateView.as_view(),name="dish-update0"),
]

awesomeproject/sudentapp/models.py
from django.db import models
from django.urls import reverse
from easy_thumbnails.fields import ThumbnailerImageField
from django.contrib.auth.models  import User
# Create your models here.
class Dish(models.Model):
    name = models.CharField(max_length=255,verbose_name="Название блюда",unique=True)
    slug = models.CharField(max_length=255,verbose_name="slug",blank=True)
    recipe = models.TextField(verbose_name="Рецепт")
    cooking_time = models.IntegerField()
    TYP_CHOICES =(
        ("S",'Суп'),
        ("G",'Гарнир'),
    )
    typ = models.CharField(max_length=2,choices=TYP_CHOICES)
    photo  = ThumbnailerImageField(blank=True,null=True)
    like = models.ManyToManyField(User)

    def pfc(self):
        ingredients = self.ingredient_set.all()
        pfc= {
            'protein':0,
            'fat':0,
            'carbohydrate':0,
            'energy':0,
        }
        for i in ingredients:
            pfc['protein']+=i.quantity*float(i.food.protein)
            pfc['fat']+=i.quantity*float(i.food.fat)
            pfc['energy']+=i.quantity*float(i.food.energy)
            pfc['carbohydrate']+=i.quantity*float(i.food.carbohydrate)
        return pfc

    def foo(self):
        return Food.objects.filter(asdop)

    def some_f(self):
        return "hello "+self.name
    def __str__(self):
        return self.name
    def get_photo_url(self):
        return self.photo['big'].url if self.photo else ''

    class Meta:
        verbose_name = "Блюдо"
        verbose_name_plural = "Блюда"
        ordering = ['-name','cooking_time']
        permissions = [
            ("my_permission","Это мое особое разрешение"),
        ]

    def get_absolute_url(self):
        return reverse('dish-detail0',kwargs={'pk':self.pk})
        #return reverse('dish-detail',kwargs={'pk':self.id})

    def save(self,*args,**kwargs):
        print("hello")
        ret = super().save(*args,**kwargs)
        print("afret real save")
        return ret

class Food(models.Model):
    name = models.CharField(max_length=255,verbose_name="Название продукта")
    protein = models.FloatField(default=0,verbose_name="Протеинов на 100г")
    fat = models.FloatField(default=0,verbose_name="Жиров на 100г")
    carbohydrate = models.FloatField(default=0,verbose_name="Жиров на 100г")
    energy  =  models.FloatField(default=0,verbose_name="ккал на 100г")
    def __str__(self):
        return self.name

class Ingredient(models.Model):
    dish = models.ForeignKey(Dish,on_delete=models.CASCADE,null=True)
    food = models.ForeignKey(Food,on_delete=models.PROTECT,null=True)
    quantity = models.FloatField()
    UNIT_CHOICE = (
        ("KG",'килиграмм'),
        ("G",'грамм'),
        ("U",'штук'),
    )
    unit = models.CharField(max_length=2,choices=UNIT_CHOICE)

    def food_name(self):
        if self.food:
            return self.food.name

from easy_thumbnails.signals import saved_file
from easy_thumbnails.signal_handlers import generate_aliases_global

saved_file.connect(generate_aliases_global)

awesomeproject/sudentapp/forms.py
from django import forms
from sudentapp.models import Dish

class DishSearchForm(forms.Form):
    name = forms.CharField(max_length=255,)

class DishForm(forms.Form):
    name = forms.CharField(max_length=255,)
    slug = forms.CharField(max_length=255)
    recipe = forms.CharField()
    cooking_time = forms.IntegerField()

class BootstrapModel(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        '''
         добавим все inputan class form-control
         '''
        super().__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':'form-control'})

class DishFormModel(BootstrapModel):
    class Meta:
        model=Dish
        fields ="__all__"

awesomeproject/sudentapp/views.py
from django.shortcuts import render
from sudentapp.models import Dish,Food,Ingredient
from django.http import HttpResponse,JsonResponse
from django.template import Template,RequestContext
from datetime import datetime as dt
from django.views.generic import TemplateView,ListView,DetailView
from django.views.generic.edit import CreateView,UpdateView
from sudentapp.forms import  DishForm,DishFormModel,DishSearchForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.db.models import Sum,F
from sudentapp.serializers import DishSerializer,IngredientSerializer
from .tasks import some_task

def index(request):
    return render(request,'index.html',{})

@login_required
def create_view(request):
    if request.method == 'GET':
        form = DishFormModel()
        return render(request,'sudentapp/dish_form.html',{'form':form})
    elif request.method == 'POST':
        context={}
        form = DishFormModel(request.POST)
        context['form'] =form
        if form.is_valid():
            dish = form.save()
            context['dish'] =dish
        else:
            pass
        return render(request,'sudentapp/dish_form.html',context)

def dish_list_json(request):
    queruset = Dish.objects.all()
    form  = DishSearchForm(request.GET)
    if form.is_valid():
        queruset = queruset.filter(name__icontains=form.cleaned_data['name'])
    #ret = list(queruset.values('id','name','recipe','cooking_time','typ'))
    ret =[]
    for dish in queruset:
        ret.append({
            'id':dish.id,
            'name':dish.name,
            'recipe':dish.recipe,
            'cooking_time':dish.cooking_time,
            'get_typ_display':dish.get_typ_display(),
            'photo':dish.photo['card'].url if dish.photo else '',
            'is_like': dish.like.filter(id=request.user.id).exists()

        })
    return JsonResponse(ret,safe=False)

def food_list_json(request):
    queruset = Food.objects.all()
    ret =[]
    for food in queruset:
        ret.append({
            'id':food.id,
            'name':food.name,
        })
    return JsonResponse(ret,safe=False)
import json

def like(request):
    data =(json.loads(request.body))
    pk = data['pk']
    d = Dish.objects.get(id=pk)
    d.like.add(request.user)
    d.save()

    return JsonResponse({'status':'OK'})






class DishDetailView(DetailView):
    model = Dish
    def get_context_data(self,*args,**kwargs):
        some_task.delay('text')

        context = super().get_context_data(*args,**kwargs)
        obj = self.get_object()

        ingredients = obj.ingredient_set.all()
        pfc= {
            'protein':0,
            'fat':0,
            'carbohydrate':0,
            'energy':0,
        }
        for i in ingredients:
            pfc['protein']+=i.quantity*float(i.food.protein)
            pfc['fat']+=i.quantity*float(i.food.fat)
            pfc['energy']+=i.quantity*float(i.food.energy)
            pfc['carbohydrate']+=i.quantity*float(i.food.carbohydrate)
        ingredients =ingredients.annotate(
            protein=F('food__protein')*F('quantity'),
            fat=F('food__fat')*F('quantity'),
            carbohydrate=F('food__carbohydrate')*F('quantity'),
            energy=F('food__energy')*F('quantity'),
        )

        pfc_aggr = ingredients.aggregate(
            p=Sum('protein'),
            f=Sum('fat'),
            c=Sum('carbohydrate'),
            e=Sum('energy'),
        )


        context['pfc_aggr']=pfc_aggr
        context['pfc']=pfc
        context['bar']=dt.now
        context['ingredients']=ingredients
        return context

class ProtectListView(LoginRequiredMixin,ListView):
    pass

class DishListView(ProtectListView):
    model = Dish
    def get_context_data(self,*args,**kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['name'] = self.request.GET.get('name')
        context['food_list'] = Food.objects.all()
        return context

    def get_queryset(self):
        queruset = super().get_queryset()
        form  = DishSearchForm(self.request.GET)
        if form.is_valid():
            queruset = queruset.filter(name__icontains=form.cleaned_data['name'])
        return queruset


class DishCreateView(CreateView):
    model = Dish
    fields = "__all__"

class DishUpdateView(UpdateView):
    model = Dish
    fields = "__all__"

class IndexView(TemplateView):
    template_name = "index.html"

from rest_framework import viewsets

class DishViewSet(viewsets.ModelViewSet):
    queryset = Dish.objects.all()
    serializer_class = DishSerializer

    def get_queryset(self):
        queruset = super().get_queryset()
        queruset = Dish.objects.all()
        form  = DishSearchForm(self.request.GET)
        if form.is_valid():
            queruset = queruset.filter(name__icontains=form.cleaned_data['name'])

        return queruset


class IngredientViewSet(viewsets.ModelViewSet):
    queryset = Ingredient.objects.all()
    serializer_class = IngredientSerializer

    def get_queryset(self):
        queruset = super().get_queryset()
        dish_id = self.request.GET.get('dish','')
        if dish_id:
            queruset = queruset.filter(dish_id=dish_id)
        return queruset

awesomeproject/sudentapp/templates/sudentapp/dish_detail.html
{% extends "base.html"%}

{%block some_name%}
<div class="row">
    <div class="col-md-12">
    <div class="card   dish_photo">
        <img src="{{object.get_photo_url}}" class="card-img" alt="...">
  <div class="card-img-overlay">
      <h5 class="card-title">{{object.name}}</h5>
    <p class="card-text"></p>
    <p class="card-text"></p>
  </div>
</div>
</div>
</div>



<div class="ingredient-row">
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"> Ингрединеты</h5>
                <ol>
                    {%for item in ingredients%}
                    <li>{{item.food.name}} -- {{item.quantity}} {{item.get_unit_display}} | {{item.energy }}</li> 
                    {%endfor%}
                </ol>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"> БЖУ</h5>
                <ol>
                    <li> Белки-- {{pfc.protein}} </li> 
                    <li> Жиры- {{pfc.fat}}</li> 
                    <li> Углеводы-- {{pfc.carbohydrate}} </li> 
                    <li> Калории--  {{pfc.energy}}</li> 
                </ol>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title"> БЖУ aggr</h5>
                <ol>

                    <li> Белки-- {{pfc_aggr.p}} </li> 
                    <li> Жиры- {{pfc_aggr.f}}</li> 
                    <li> Углеводы-- {{pfc_aggr.c}} </li> 
                    <li> Калории--  {{pfc_aggr.e}}</li> 
                </ol>
            </div>
        </div>
    </div>
</div>
</div>

<div class="row">
    <div class="col-md-12">
        <h2>Рецепт</h2>
<div>{{object.recipe|linebreaks}}</div>
</div>
</div>
<script>

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + 'test_channel'
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            alert(e)
        };
          chatSocket.send(JSON.stringify({
                'message': "test"
            }));
</script>
{%endblock%}

awesomeproject/sudentapp/templates/sudentapp/dish_form.html
{% extends "base.html"%}

{%block some_name%}
<div class="row">
    <div class="col-md-12">
        <form method="POST" >
        <div class="mb-3 row">
            <label  class="col-sm-2 col-form-label">Название </label>
            <div class="col-sm-10">
                <input value="{{name}}" name="name" class="form-control">
            </div>
        </div>
        {{error}}
        <div class="mb-3 row">
            <label  class="col-sm-2 col-form-label">Рецеп</label>
            <div class="col-sm-10">
                <textarea  name="recipe" class="form-control">{{recipe}}</textarea>
            </div>
        </div>
        <div class="mb-3 row">
            <label  class="col-sm-2 col-form-label">Время приготовления</label>
            <div class="col-sm-10">
                <input name="cooking_time" class="form-control" value="{{cooking_time}}">
            </div>
        </div>
        <div class="mb-3 row">
            <label  class="col-sm-2 col-form-label">Тип блюда</label>
            <div class="col-sm-10">
                <select name="typ" class="form-control">
                    <option value="S"> Суп</option>
                    <option value="G"> Гарнир</option>
                </select>
            </div>
        </div>


        {% csrf_token %}
        <button class="btn btn-primary"> сохранить</button>
        </form>

        <form method="POST" >
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary"> сохранить2</button>
        </form>
        </div>
        <h1> НОВЫЙ ДИШ {{dish}}</h1>
</div>


{%endblock%}

awesomeproject/sudentapp/templates/sudentapp/dish_list.html
{% extends "base.html"%}

{%block some_name%}
<div class="row">
    <div class="col-md-10 col-sm-12">
        <div class="row row-cols-1  row-cols-sm-2 row-cols-md-3 g-4">
            {% for dish in object_list%}
            <div class="col">
                <div class="card h-100" > 
                    {% if dish.photo%}
                    <img class="card-img-top" src="{{dish.photo.card.url}}">
                    {%else %}
                    фото нет
                    {%endif%}
                    <div class="card-body">
                        <h5 class="card-title"> {{dish.name}}</h5>
                        <p>{{dish.get_typ_display}} </p>
                        <p>  {{dish.cooking_time}} </p>
                        <p>  {%for  ing in dish.ingredient_set.all %} 
                        <div> {{ing.food.name }}|  {{ing.quantity}}</div>
                        {%endfor%}
                        {% lorem 1 p %} 
                        </p>
                        </td>
                        <a href=" {{ dish.get_absolute_url }}" class="btn btn-primary">подробнее</a>
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>
    </div>

</div>
{%endblock%}