awesomeproject/awesomeproject/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from sudentapp.views import IndexView
from django.conf import settings
from django.conf.urls.static import static

from  django.contrib.auth.views import LoginView
from rest_framework.routers import DefaultRouter
from sudentapp.views import DishViewSet,IngredientViewSet

router = DefaultRouter()
router.register(r'dish', DishViewSet)
router.register(r'ingredient',IngredientViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('',IndexView.as_view()),
    path('accounts/login/',LoginView.as_view(template_name="login.html"),name="login"),
    path('dish/',include("sudentapp.urls")),
    path('admin/', admin.site.urls),
]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

awesomeproject/sudentapp/urls.py
from django.urls import path
from sudentapp.views import( DishListView,
                            DishDetailView,
                            DishCreateView,
                            create_view,
                            DishUpdateView,
                            dish_list_json,
                            food_list_json,
                            like
                            )

urlpatterns = [
    path('',DishListView.as_view(),name="dish-list0"),
    path('like/',like,name="dish-like"),
    path('json/',dish_list_json,name="dish-list-json"),
    path('food/json/',food_list_json,name="food-list-json"),
    #path('create',DishCreateView.as_view(),name="dish-create"),
    path('create',create_view,name="dish-create0"),
    path('<int:pk>/class',DishDetailView.as_view(),name="dish-detail0"),
    path('<int:pk>/update',DishUpdateView.as_view(),name="dish-update0"),
]

awesomeproject/sudentapp/models.py
from django.db import models
from django.urls import reverse
from easy_thumbnails.fields import ThumbnailerImageField
from django.contrib.auth.models  import User
# Create your models here.
class Dish(models.Model):
    name = models.CharField(max_length=255,verbose_name="Название блюда",unique=True)
    slug = models.CharField(max_length=255,verbose_name="slug",blank=True)
    recipe = models.TextField(verbose_name="Рецепт")
    cooking_time = models.IntegerField()
    TYP_CHOICES =(
        ("S",'Суп'),
        ("G",'Гарнир'),
    )
    typ = models.CharField(max_length=2,choices=TYP_CHOICES)
    photo  = ThumbnailerImageField(blank=True,null=True)
    like = models.ManyToManyField(User)

    def pfc(self):
        ingredients = self.ingredient_set.all()
        pfc= {
            'protein':0,
            'fat':0,
            'carbohydrate':0,
            'energy':0,
        }
        for i in ingredients:
            pfc['protein']+=i.quantity*float(i.food.protein)
            pfc['fat']+=i.quantity*float(i.food.fat)
            pfc['energy']+=i.quantity*float(i.food.energy)
            pfc['carbohydrate']+=i.quantity*float(i.food.carbohydrate)
        return pfc

    def foo(self):
        return Food.objects.filter(asdop)

    def some_f(self):
        return "hello "+self.name
    def __str__(self):
        return self.name
    def get_photo_url(self):
        return self.photo['big'].url if self.photo else ''

    class Meta:
        verbose_name = "Блюдо"
        verbose_name_plural = "Блюда"
        ordering = ['-name','cooking_time']
        permissions = [
            ("my_permission","Это мое особое разрешение"),
        ]

    def get_absolute_url(self):
        return reverse('dish-detail0',kwargs={'pk':self.pk})
        #return reverse('dish-detail',kwargs={'pk':self.id})

    def save(self,*args,**kwargs):
        print("hello")
        ret = super().save(*args,**kwargs)
        print("afret real save")
        return ret

class Food(models.Model):
    name = models.CharField(max_length=255,verbose_name="Название продукта")
    protein = models.FloatField(default=0,verbose_name="Протеинов на 100г")
    fat = models.FloatField(default=0,verbose_name="Жиров на 100г")
    carbohydrate = models.FloatField(default=0,verbose_name="Жиров на 100г")
    energy  =  models.FloatField(default=0,verbose_name="ккал на 100г")
    def __str__(self):
        return self.name

class Ingredient(models.Model):
    dish = models.ForeignKey(Dish,on_delete=models.CASCADE,null=True)
    food = models.ForeignKey(Food,on_delete=models.PROTECT,null=True)
    quantity = models.FloatField()
    UNIT_CHOICE = (
        ("KG",'килиграмм'),
        ("G",'грамм'),
        ("U",'штук'),
    )
    unit = models.CharField(max_length=2,choices=UNIT_CHOICE)

    def food_name(self):
        if self.food:
            return self.food.name

from easy_thumbnails.signals import saved_file
from easy_thumbnails.signal_handlers import generate_aliases_global

saved_file.connect(generate_aliases_global)

awesomeproject/sudentapp/forms.py
from django import forms
from sudentapp.models import Dish

class DishSearchForm(forms.Form):
    name = forms.CharField(max_length=255,)

class DishForm(forms.Form):
    name = forms.CharField(max_length=255,)
    slug = forms.CharField(max_length=255)
    recipe = forms.CharField()
    cooking_time = forms.IntegerField()

class BootstrapModel(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        '''
         добавим все inputan class form-control
         '''
        super().__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class':'form-control'})

class DishFormModel(BootstrapModel):
    class Meta:
        model=Dish
        fields ="__all__"

awesomeproject/sudentapp/views.py
from django.shortcuts import render
from sudentapp.models import Dish,Food,Ingredient
from django.http import HttpResponse,JsonResponse
from django.template import Template,RequestContext
from datetime import datetime as dt
from django.views.generic import TemplateView,ListView,DetailView
from django.views.generic.edit import CreateView,UpdateView
from sudentapp.forms import  DishForm,DishFormModel,DishSearchForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.db.models import Sum,F
from sudentapp.serializers import DishSerializer,IngredientSerializer
from .tasks import some_task

def index(request):
    return render(request,'index.html',{})

@login_required
def create_view(request):
    if request.method == 'GET':
        form = DishFormModel()
        return render(request,'sudentapp/dish_form.html',{'form':form})
    elif request.method == 'POST':
        context={}
        form = DishFormModel(request.POST)
        context['form'] =form
        if form.is_valid():
            dish = form.save()
            context['dish'] =dish
        else:
            pass
        return render(request,'sudentapp/dish_form.html',context)

def dish_list_json(request):
    queruset = Dish.objects.all()
    form  = DishSearchForm(request.GET)
    if form.is_valid():
        queruset = queruset.filter(name__icontains=form.cleaned_data['name'])
    #ret = list(queruset.values('id','name','recipe','cooking_time','typ'))
    ret =[]
    for dish in queruset:
        ret.append({
            'id':dish.id,
            'name':dish.name,
            'recipe':dish.recipe,
            'cooking_time':dish.cooking_time,
            'get_typ_display':dish.get_typ_display(),
            'photo':dish.photo['card'].url if dish.photo else '',
            'is_like': dish.like.filter(id=request.user.id).exists()

        })
    return JsonResponse(ret,safe=False)

def food_list_json(request):
    queruset = Food.objects.all()
    ret =[]
    for food in queruset:
        ret.append({
            'id':food.id,
            'name':food.name,
        })
    return JsonResponse(ret,safe=False)
import json

def like(request):
    data =(json.loads(request.body))
    pk = data['pk']
    d = Dish.objects.get(id=pk)
    d.like.add(request.user)
    d.save()

    return JsonResponse({'status':'OK'})






class DishDetailView(DetailView):
    model = Dish
    def get_context_data(self,*args,**kwargs):
        some_task.delay('text')

        context = super().get_context_data(*args,**kwargs)
        obj = self.get_object()

        ingredients = obj.ingredient_set.all()
        pfc= {
            'protein':0,
            'fat':0,
            'carbohydrate':0,
            'energy':0,
        }
        for i in ingredients:
            pfc['protein']+=i.quantity*float(i.food.protein)
            pfc['fat']+=i.quantity*float(i.food.fat)
            pfc['energy']+=i.quantity*float(i.food.energy)
            pfc['carbohydrate']+=i.quantity*float(i.food.carbohydrate)
        ingredients =ingredients.annotate(
            protein=F('food__protein')*F('quantity'),
            fat=F('food__fat')*F('quantity'),
            carbohydrate=F('food__carbohydrate')*F('quantity'),
            energy=F('food__energy')*F('quantity'),
        )

        pfc_aggr = ingredients.aggregate(
            p=Sum('protein'),
            f=Sum('fat'),
            c=Sum('carbohydrate'),
            e=Sum('energy'),
        )


        context['pfc_aggr']=pfc_aggr
        context['pfc']=pfc
        context['bar']=dt.now
        context['ingredients']=ingredients
        return context

class ProtectListView(LoginRequiredMixin,ListView):
    pass

class DishListView(ProtectListView):
    model = Dish
    def get_context_data(self,*args,**kwargs):
        context = super().get_context_data(*args,**kwargs)
        context['name'] = self.request.GET.get('name')
        context['food_list'] = Food.objects.all()
        return context

    def get_queryset(self):
        queruset = super().get_queryset()
        form  = DishSearchForm(self.request.GET)
        if form.is_valid():
            queruset = queruset.filter(name__icontains=form.cleaned_data['name'])
        return queruset


class DishCreateView(CreateView):
    model = Dish
    fields = "__all__"

class DishUpdateView(UpdateView):
    model = Dish
    fields = "__all__"

class IndexView(TemplateView):
    template_name = "index.html"

from rest_framework import viewsets

class DishViewSet(viewsets.ModelViewSet):
    queryset = Dish.objects.all()
    serializer_class = DishSerializer

    def get_queryset(self):
        queruset = super().get_queryset()
        queruset = Dish.objects.all()
        form  = DishSearchForm(self.request.GET)
        if form.is_valid():
            queruset = queruset.filter(name__icontains=form.cleaned_data['name'])

        return queruset


class IngredientViewSet(viewsets.ModelViewSet):
    queryset = Ingredient.objects.all()
    serializer_class = IngredientSerializer

    def get_queryset(self):
        queruset = super().get_queryset()
        dish_id = self.request.GET.get('dish','')
        if dish_id:
            queruset = queruset.filter(dish_id=dish_id)
        return queruset

awesomeproject/sudentapp/templates/base.html
{%load static%}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link href="{% static 'style.css'%}" rel="stylesheet" >
<script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
    </head>
    <body >
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="/">Кухня</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url  'dish-list0' %}">Блюда</a>
                        </li> 
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                      Dropdown
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled">Disabled</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        <div class="container">
            {%block some_name%}

                    hello это сайт про еду
            {%endblock%}
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="{%static 'main.js'%} "></script>
    </body>
</html>

awesomeproject/sudentapp/templates/foo.html
{% extends "base.html"%}

{%block some_name%}
<div class="row">
    <div class="col-md-10 col-sm-12">
        <table class="table table-hover" >
            <thead>
                <tr>
                    <th>  id</th>
                    <th>  </th>
                    <th>  name </th>
                    <th> Тип </th>
                    <th> время готовки </th>
                    <th>  </th>
                </tr>
            </thead>
            {% for dish in dish_list%}
            <tr> 
                <td> {{dish.id}} </td>
                <td> 
                    {% if dish.photo%}
                    <img src="{{dish.photo.url}}">
                    {%else %}
                    фото нет
                    {%endif%}

                </td>
                <td> <a href="{{ dish.get_absolute_url }}">{{dish.name}} </a> </td>
                <td>{{dish.get_typ_display}} </td>
                <td>  {{dish.cooking_time}} </td>
                <td>  {%for  ing in dish.ingredient_set.all %} 
                    <div> {{ing.food.name }}|  {{ing.quantity}}</div>
                    {%endfor%}
                </td>
            </tr>
            {%endfor%}
        </table >
    </div>

</div>
{%endblock%}

awesomeproject/sudentapp/templates/index.html
<!DOCTYPE html><html lang=""><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="/favicon.ico"><title>dish-app</title><link href="/static/js/about.a05b45ec.js" rel="prefetch"><link href="/static/css/app.028e6204.css" rel="preload" as="style"><link href="/static/css/chunk-vendors.8bda0bd5.css" rel="preload" as="style"><link href="/static/js/app.fd220afc.js" rel="preload" as="script"><link href="/static/js/chunk-vendors.cebfab52.js" rel="preload" as="script"><link href="/static/css/chunk-vendors.8bda0bd5.css" rel="stylesheet"><link href="/static/css/app.028e6204.css" rel="stylesheet"></head><body><noscript><strong>We're sorry but dish-app doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div><script src="/static/js/chunk-vendors.cebfab52.js"></script><script src="/static/js/app.fd220afc.js"></script></body></html>

awesomeproject/sudentapp/templates/login.html
{% extends "base.html" %}

{% block some_name %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>


{% endblock %}

awesomeproject/sudentapp/templates/time.html
<div class="timer">
    <div > текущее время:</div>
    <div>{{bar}}</div>
</div>